# ReadTheDocs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with Python 3.9
python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Build PDFs
formats:
  - pdf
  - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Optionally set the version of pip to use
python:
  pip_install: true
  extra_requirements:
    - docs

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optionally provide the default version that will be shown at the root of the site
default_version: latest

# Optionally set the version name to a branch name, tag name, or commit hash
# for the "latest" version, replacing the default of using the latest tag
default_version: latest

# Optionally set the version name to a branch name, tag name, or commit hash
# for the "latest" version, replacing the default of using the latest tag
# default_version: main

# Optionally set the version name to a branch name, tag name, or commit hash
# for the "latest" version, replacing the default of using the latest tag
# default_version: master
