# ReadTheDocs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with Python 3.9
python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Build PDFs and EPUB
formats:
  - pdf
  - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Set the default version that will be shown at the root of the site
default_version: latest
