# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Install the package and documentation dependencies
install:
  - method: pip
    path: .
    extra_requirements:
      - docs

# Set the OS to Ubuntu 20.04
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  environment:
    PYTHONPATH: $PYTHONPATH:$READTHEDOCS_PROJECT_DIR

# Additional build options
formats:
  - pdf
  - epub

# Submodules
submodules:
  include:
    - docs
